export const SCREENS = {
  // AUTH SCREEN
  LOGIN: "Login",
  SIGN_UP: "SignUp",
  DRIVER_SIGNUP : "DriverSignUp",
  FORGOT:"ForgotPass",
  NUMBER_PLATE:"NumberPlate",
  CERTIFICATE:"Certificate",
  VECHILE_YEAR:"VechileYear",

  // Bottom Screen
  HOME: "Home",
  NOTIFICATION: "Notification",
  PROFILE: "Profile",
  SELECT_TRANSPORT:"SelectTransport",

  NAV_SCREEN:"NavigationScreen",
  My_ACTIVITY:'MyActivity',
  DELIVERY_DETAILS:"DeliveryDetails",
  PAYMENT_METHOD:'PaymentMethod',
  MAIL_DELIVERED:'MailDelivered',
  CHAT:'Chat',
  RIDE_DETAILS:"RideDetails",
  BOOK_RIDE:"BookRide",
  E_TICKET:'ETicket',
  SCAN_QR:'ScanQR',
  BUS_DETAIL:"BusDetails",

  SETTING:'Setting',
  PRIVACY:'Privacy',
  TERMS:'Terms',
  ABOUT:'About',
  MY_CARD:'MyCard',
  ADD_CARD:'AddNewCard',
  CONTACT_US:'ContactUs',

  EDIT_PROFILE:"EditProfile",
  CHANGE_PASSWORD:"ChangePassword",
  HISTORY:'History',

  HOME_DRIVER:"HomeDriver",
  REGISTRATION:"Registration",
  VECHILE_INFO:"VechileInfo",
  ID_CARD : "IDCard",
  ID_CONFIRMATION:"IDConfirmation",
  DRIVER_LICENSE:"DriverLicence",
  LEGAL_CONSENT:'LegalConsent',
  POST_HISTORY:"PostHistory",
  HISTORY_DETAIL:"HistoryDetail",
  DRIVER_RIDE_DETAIL:'DriverRideDetail',
  ACCEPT_RIDE:'AcceptRide',
  NAV_DRAVER_SCREEN:"NavigationDriverScreen",
  ACTIVITY_DETAILS:"ActivityDetail",
  My_WALLET:"MyWallet",
  ADD_ACCOUNT:"AddAccount",
  MY_DOCUMENTS:"MyDocuments",
  ID_CARD_DOCS:"IDCardDocs",
  ID_CONFIRM_DOCS:"IDConfirmationDocs",
  DRIVER_LICENSE_DOCS:"DriverLicenseDocs",
  VECHILE_INFO_DOCS:"VechileInfoDocs",
  BUS_DETAIL2:"BusDetails2",
  E_TICKET2:"ETicket2",
  DRIVER_MAIL_DETAIL:"DriverMailDetail",
  ACCEPT_MAIL_RIDE:"AcceptMailRide",
  NAV_DRAVER_MAIL_SCREEN:"NavigationDriverMailScreen",
  PASSENGER:"Passengers"
 } ;
